---
title: "GEDE_explore"
author: "Shaopeng"
date: "2024-11-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("recount3")
library("limma")
library("SummarizedExperiment")  # assays function come from here
source("GEDE_utils.R")
library(pheatmap)
library(DESeq2)
```



### Download data
```{r recounts_data_explore, message = FALSE}
all_projects <- available_projects()
human_projects = subset(all_projects, organism=="human")
print(dim(human_projects))
print(table(human_projects$project_home))
# 32 gtex and 33 tcga and 8677 sra
# However, those 3 groups have different labels for disease condition. Sra is hard to use, we keep the rest 2
selected_proj = subset(human_projects, organism=="human" & project_home == "data_sources/tcga")
table(selected_proj$project)
print(dim(selected_proj))
# those matched conditions can be used to test model performance (?)
```



### build RSE object for target studies and save Rdata
```{r use_tcga_luad_for_test, message = FALSE}
## TCGA LUAD and LUSC
proj_luad <- subset(selected_proj, project == "LUAD" & project_home == "data_sources/tcga")
proj_lusc <- subset(selected_proj, project == "LUSC" & project_home == "data_sources/tcga")

# we can manually create RSE object from 1) raw matrix; 2) metadata; and 3) GRange from gene annotations
# But not necessary for now, as we have many from recount3
rse_luad <- create_rse(proj_luad)
rse_lusc <- create_rse(proj_lusc)

# merge them (make sure rows are equal)
if (all(rownames(rse_luad) == rownames(rse_lusc))) {
    rse_gene <- cbind(rse_luad, rse_lusc)
} else {
    stop("Row names (features) do not match between rse1 and rse2.")
}

print(dim(rse_gene))
print(assayNames(rse_gene))
print(assay(rse_gene)[1:3,1:3])
# number of metadata is too high
print(dim(rse_gene@colData))

# filter non-coding gene
if ("gene_type" %in% names(mcols(rowRanges(rse_gene)))) {
  coding_genes <- rowRanges(rse_gene)$gene_type == "protein_coding"
  rse_gene <- rse_gene[coding_genes, ]
}

# now 22k genes
print(dim(rse_gene))
print(table(rse_gene$tcga.gdc_cases.project.name))
# release space
rm(rse_luad, rse_lusc)

# save data
save(rse_gene, file="pooled_gcta_luad_and_lusc.Rdata")
```



### Examine the data
```{r data_prep, message = FALSE}
# prepare data object: a list containing count and groups
Data <- read_data(path="pooled_gcta_luad_and_lusc.Rdata", metaVar = "tcga.gdc_cases.project.name", to_remove = NULL)
str(Data)


### Examine samples and exclude outlier
data <- Data$counts
group <- Data$group
print("Full loaded data")
dim(data)

# we don't remove empty rows/cols here: rows will be removed in next step, cols are kept for cross-data consistency


# 1. by total expression
col_sums <- colSums(data)
boxplot(col_sums, main = "Boxplot of Total Expression by Sample", horizontal = TRUE)
lower_bound <- quantile(col_sums, 0.25) - 1.5 * IQR(col_sums)
upper_bound <- quantile(col_sums, 0.75) + 1.5 * IQR(col_sums)
outlier_indices <- which(col_sums < lower_bound | col_sums > upper_bound)

data <- data[, -outlier_indices]
group <- group[-outlier_indices]
print(paste0("Remove ", length(outlier_indices) ," low depth data"))
dim(data)


# 2. PCA check
log_data = log2(data+1)
data_t = t(log_data)
pca_result <- prcomp(data_t, center = TRUE, scale. = FALSE)
pca_summary <- summary(pca_result)
top_10 <- pca_summary$importance[, 1:10]
print(top_10)

# plot PCA
group_colors <- as.numeric(as.factor(group))  # Convert group categories to numeric
color_palette <- rainbow(length(unique(group)))  # Create a color palette

plot(pca_result$x[, 1], pca_result$x[, 2], 
     xlab = "PC1", ylab = "PC2", 
     main = "PCA of Samples",
     pch = 19, col = color_palette[group_colors])

legend("topright", legend = unique(group), 
       col = color_palette, pch = 19, title = "Groups")



# 3. check for normality at gene level
df1 = log_data[ , which(group=="Lung Adenocarcinoma")]
df2 = log_data[ , which(group=="Lung Squamous Cell Carcinoma")]

abnormal_gene1 = check_normality(df1)
abnormal_gene2 = check_normality(df2)

plot({
  qqnorm(df1['ENSG00000269713.7', ], main = "Q-Q Plot for ENSG00000269713.7")
  #qqline(df1['ENSG00000269713.7', ], col = "red")   # this will 
})

dim(df1)
length(abnormal_gene1)
length(abnormal_gene2)


# update Data for output
Data$group <- group
Data$counts <- data

plot(pca_result$x[, 1], pca_result$x[, 2], 
     xlab = "PC1", ylab = "PC2", 
     main = "PCA of Samples",
     pch = 19, col = "blue")
```



### call data_prep to make them ready for GEDE analysis
```{r data_explore, message = FALSE}
# DE preparation (no difference for the LUAD and LUSC case)
Data <- metadata_binarize(Data, 'Lung Adenocarcinoma', 'Lung Squamous Cell Carcinoma', to_remove = NULL)
Data <- dea_prep(Data)
dim(Data$counts)

# selection and normalization should be after the outlier removing step
Data <- gene_selection(Data, zero_threshold = 0.9)  # 0.9 is the default
dim(Data$counts)


# let's see how normality works for voom transformation
log_data = Data$voom_counts
group = Data$group
df1 = log_data[ , which(group=="groupLungAdenocarcinoma")]
df2 = log_data[ , which(group=="groupLungSquamousCellCarcinoma")]

abnormal_gene1 = check_normality(df1)
abnormal_gene2 = check_normality(df2)
dim(df1)
length(abnormal_gene1)
length(abnormal_gene2)

plot({
  qqnorm(df1['ENSG00000213240.8', ], main = "Q-Q Plot for ENSG00000213240.8")
  #qqline(df1['ENSG00000213240.8', ], col = "red")
})

# save file
save(Data, file="TCGA_lung_data.RData")
```



### next chapter


